data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=my-root-password
    - MYSQL_DATABASE=guestbook
    - MYSQL_USER=guestbook-admin
    - MYSQL_PASSWORD=my-guestbook-admin-password

app:
  extends:
    file: docker-compose-common.yml
    service: app
  expose:
    - "8000"
  links:
    - db:db
  command: gunicorn app:app -b 0.0.0.0:8000

web:
  extends:
    file: docker-compose-common.yml
    service: web
  ports:
    # Publish the port so it's visible on the host
    - "80:80"
  links:
    - app:app
