db:
  extends:
    file: docker-compose-common.yml
    service: db
  environment:
    - MYSQL_ROOT_PASSWORD=my-root-password
    - MYSQL_DATABASE=guestbook
    - MYSQL_USER=guestbook-admin
    - MYSQL_PASSWORD=my-guestbook-admin-password

app:
  extends:
    file: docker-compose-common.yml
    service: app
  volumes:
    - app:/src
  links:
    - db:db
  command: gunicorn --reload app:app -b 0.0.0.0:8000

web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - app:app
