app:
  extends:
    file: docker-compose-common.yml
    service: app
  command: gunicorn app:app -b 0.0.0.0:8000

web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - app:app
