app:
  extends:
    file: docker-compose-common.yml
    service: app
  volumes:
    - app:/src
  command: gunicorn --reload app:app -b 0.0.0.0:8000

web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - app:app
